version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - DOMAIN=https://<domain>
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - ADMIN_TOKEN=<admin_token>
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_FROM=no-reply@<domain>
      - SMTP_PORT=465
      - SMTP_SSL=false
      - SMTP_EXPLICIT_TLS=true
      - SMTP_USERNAME=apikey
      - SMTP_PASSWORD=<sendgrid_apikey>
      - SMTP_AUTH_MECHANISM="Login"
      # - SIGNUPS_ALLOWED=false
      # - INVITATIONS_ALLOWED=false
    volumes:
      - ./vw-data:/data
    ports:
      - "81:80"
      - "3012:3012"

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/vaultwarden.conf:ro
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    restart: unless-stopped
    ports:
      - "82:80"
      - "443:443"
    environment:
      - DOMAIN=https://<domain>  # Your domain.
      - LOG_FILE=/data/access.log